name: Update Environment Variables

on: [push]

jobs:
  update-env:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install dotenv

    - name: Update script.js
      run: |
        sed -i '1s/^/require("dotenv").config();\n/' public/script.js
        sed -i 's/YOUR_SUPABASE_URL/process.env.SUPABASE_URL/' public/script.js
        sed -i 's/YOUR_SUPABASE_ANON_KEY/process.env.SUPABASE_ANON_KEY/' public/script.js

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add public/script.js
        git commit -m 'Update script.js to use environment variables'
        git push
